name: Performance Tests

on:
  workflow_dispatch:
    inputs:
      test_dnsrecord_count:
        description: 'Number of DNSSRecords to create in each workspace'
        required: false
        default: '2'
      test_ingress_count:
        description: 'Number of Ingresses to create in each workspace'
        required: false
        default: '2'
      test_workspace_count:
        description: 'Number of Workspaces to create'
        required: false
        default: '2'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  ingress_test:
    name: Ingress Load Test
    environment: ${{ inputs.environment || 'unstable' }}
    concurrency: ${{ inputs.environment || 'unstable' }}
    runs-on: ubuntu-20.04
    env:
      TEST_DNSRECORD_COUNT: ${{ github.event.inputs.test_dnsrecord_count}}
      TEST_INGRESS_COUNT: ${{ github.event.inputs.test_ingress_count }}
      TEST_WORKSPACE_COUNT: ${{ github.event.inputs.test_workspace_count}}
      AWS_DNS_PUBLIC_ZONE_ID: ${{ secrets.AWS_DNS_PUBLIC_ZONE_ID }}
      GLBC_DOMAIN: ${{ secrets.GLBC_DOMAIN }}
      GLBC_ENABLE_CUSTOM_HOSTS: ${{ secrets.GLBC_ENABLE_CUSTOM_HOSTS }}
      GLBC_EXPORT: ${{ secrets.GLBC_EXPORT }}
      GLBC_WORKSPACE: ${{ secrets.GLBC_WORKSPACE }}
      TEST_WORKSPACE: ${{ secrets.TEST_WORKSPACE }}
      TEST_TAGS: performance,ingress
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.18
      - name: Setup Kubeconfig
        run: |
          make generate-test-oidc-kubeconfig \
              TEST_OIDC_KUBECONFIG=test.kubeconfig \
              TEST_KUBE_HOST=${{ secrets.TEST_KUBE_HOST }} \
              TEST_KUBE_OIDC_ISSUER_URL=${{ secrets.TEST_KUBE_OIDC_ISSUER_URL }} \
              TEST_KUBE_OIDC_CLIENT_ID=${{ secrets.TEST_KUBE_OIDC_CLIENT_ID }} \
              TEST_KUBE_OIDC_CLIENT_SECRET=${{ secrets.TEST_KUBE_OIDC_CLIENT_SECRET }}
          kubectl config --kubeconfig=test.kubeconfig get-contexts
          export KUBECONFIG="$(pwd)"/test.kubeconfig
          echo "KUBECONFIG=${KUBECONFIG}" >> $GITHUB_ENV
      - name: Run performance tests
        run: |
          export KUBECONFIG=${{ env.KUBECONFIG }}
          echo "TEST_INGRESS_COUNT = ${{ env.TEST_INGRESS_COUNT }}"
          echo "TEST_DNSRECORD_COUNT = ${{ env.TEST_DNSRECORD_COUNT }}"
          echo "TEST_WORKSPACE_COUNT = ${{ env.TEST_WORKSPACE_COUNT }}"
          echo "AWS_DNS_PUBLIC_ZONE_ID = ${{ env.AWS_DNS_PUBLIC_ZONE_ID }}"
          echo "GLBC_DOMAIN = ${{ env.GLBC_DOMAIN }}"
          make performance TEST_TAGS=${{ env.TEST_TAGS }}

  dns_record_test:
    name: DNSRecord Load Test
    environment: ${{ inputs.environment || 'unstable' }}
    concurrency: ${{ inputs.environment || 'unstable' }}
    runs-on: ubuntu-20.04
    env:
      TEST_DNSRECORD_COUNT: ${{ github.event.inputs.test_dnsrecord_count}}
      TEST_INGRESS_COUNT: ${{ github.event.inputs.test_ingress_count }}
      TEST_WORKSPACE_COUNT: ${{ github.event.inputs.test_workspace_count}}
      AWS_DNS_PUBLIC_ZONE_ID: ${{ secrets.AWS_DNS_PUBLIC_ZONE_ID }}
      GLBC_DOMAIN: ${{ secrets.GLBC_DOMAIN }}
      GLBC_ENABLE_CUSTOM_HOSTS: ${{ secrets.GLBC_ENABLE_CUSTOM_HOSTS }}
      GLBC_EXPORT: ${{ secrets.GLBC_EXPORT }}
      GLBC_WORKSPACE: ${{ secrets.GLBC_WORKSPACE }}
      TEST_WORKSPACE: ${{ secrets.TEST_WORKSPACE }}
      TEST_TAGS: performance,dnsrecord
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.18
      - name: Setup Kubeconfig
        run: |
          make generate-test-oidc-kubeconfig \
              TEST_OIDC_KUBECONFIG=test.kubeconfig \
              TEST_KUBE_HOST=${{ secrets.TEST_KUBE_HOST }} \
              TEST_KUBE_OIDC_ISSUER_URL=${{ secrets.TEST_KUBE_OIDC_ISSUER_URL }} \
              TEST_KUBE_OIDC_CLIENT_ID=${{ secrets.TEST_KUBE_OIDC_CLIENT_ID }} \
              TEST_KUBE_OIDC_CLIENT_SECRET=${{ secrets.TEST_KUBE_OIDC_CLIENT_SECRET }}
          kubectl config --kubeconfig=test.kubeconfig get-contexts
          export KUBECONFIG="$(pwd)"/test.kubeconfig
          echo "KUBECONFIG=${KUBECONFIG}" >> $GITHUB_ENV
      - name: Run performance tests
        run: |
          export KUBECONFIG=${{ env.KUBECONFIG }}
          echo "TEST_INGRESS_COUNT = ${{ env.TEST_INGRESS_COUNT }}"
          echo "TEST_DNSRECORD_COUNT = ${{ env.TEST_DNSRECORD_COUNT }}"
          echo "TEST_WORKSPACE_COUNT = ${{ env.TEST_WORKSPACE_COUNT }}"
          echo "AWS_DNS_PUBLIC_ZONE_ID = ${{ env.AWS_DNS_PUBLIC_ZONE_ID }}"
          echo "GLBC_DOMAIN = ${{ env.GLBC_DOMAIN }}"
          make performance TEST_TAGS=${{ env.TEST_TAGS }}
